#!/bin/bash

# For generating Kubernetes API typescript classes.
# clone https://github.com/kubernetes-client/gen.git
# ./openapi/typescript.sh dist/generated tools/settings

# Kubernetes branch to get the OpenAPI spec from.
export KUBERNETES_BRANCH="release-1.10"

# client version for packaging and releasing. It can
# be different than SPEC_VERSION.
export CLIENT_VERSION="0.1.0-SNAPSHOT"

# Name of the release package
export PACKAGE_NAME="io.kubernetes.client"
